Factory/Models/EngineerMachine.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models;

public class EngineerMachine
{
  public int EngineerMachineId { get; set; }
  public int EngineerId { get; set; }
  public int MachineId { get; set; }
  public Engineer Engineer { get; set; }
  public Machine Machine { get; set; }
}

Factory/Models/Engineers.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models;

public class Engineer
{
  public int EngineerId { get; set; }
  [Required(ErrorMessage = "Please enter a name for this employee.")]
  public string EngineerName { get; set; }
  public List<EngineerMachine> JoinEntities { get; set; }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachines { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }
  }
}

Factory/Models/Machines.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models;

public class Machine
{
  public int MachineId { get; set; }
  [Required(ErrorMessage = "Please enter a name for the machine.")]
  public string MachineName { get; set; }
  public List<EngineerMachine> JoinEntities { get; set; }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace Factory.Controllers;

public class EngineersController : Controller
{
  private readonly FactoryContext _db;

  public EngineersController(FactoryContext db)
  {
    _db = db;
  }
  
  public ActionResult Index()
  {
    return View(_db.Engineers.ToList());
  }

  public ActionResult Create()
  {
    return View();
  }

  [HttpPost]
  public ActionResult Create(Engineer engineer)
  {
    if (!ModelState.IsValid)
    {
      return View(engineer);
    }
    else
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }

  public ActionResult Details(int id)
  {
    ViewBag.Machines = _db.Machines.ToList();
    Engineer thisEngineer = _db.Engineers
      .Include(engineer => engineer.JoinEntities)
      .ThenInclude(join => join.Machine)
      .FirstOrDefault(engineer => engineer.EngineerId == id);
    return View(thisEngineer);
  }

  public ActionResult AddMachine(int id)
  {
    Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
    ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
    return View(thisEngineer);
  }

  [HttpPost]
  public ActionResult AddMachine(Engineer engineer, int machineId)
  {
    #nullable enable
    EngineerMachine? joinEntity =_db.EngineerMachines.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
    #nullable disable
    if (joinEntity == null && machineId != 0)
    {
      _db.EngineerMachines.Add(new EngineerMachine() { MachineId = machineId, EngineerId = engineer.EngineerId });
      _db.SaveChanges();
    }
    return RedirectToAction("Details", new { id = engineer.EngineerId});
  }

  public ActionResult Edit(int id)
  {
    Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
    return View(thisEngineer);
  }

  [HttpPost]
  public ActionResult Edit(Engineer engineer)
  {
    if (!ModelState.IsValid)
    {
      return View(engineer);
    }
    else
    {
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }
  }

  public ActionResult Delete(int id)
  {
    Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
    return View(thisEngineer);
  }

  [HttpPost, ActionName("Delete")]
  public ActionResult DeleteConfirmed(int id)
  {
    Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
    _db.Engineers.Remove(thisEngineer);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }

  [HttpPost]
  public ActionResult DeleteMachine(int joinId)
  {
    EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
    _db.EngineerMachines.Remove(joinEntry);
    _db.SaveChanges();
    return RedirectToAction("Details", new { id = joinEntry.EngineerId });
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
public class HomeController : Controller
    {
      private readonly FactoryContext _db;

      public HomeController(FactoryContext db)
      {
        _db = db;
      }

      [HttpGet("/")]
      public ActionResult Index()
      {
        Engineer[] engineers = _db.Engineers.ToArray();
        Machine[] machines = _db.Machines.ToArray();
        Dictionary<string, object[]> model = new Dictionary<string, object[]>();
        model.Add("engineers", engineers);
        model.Add("machines", machines); 
        return View(model);
      }
    }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace Factory.Controllers;

public class MachinesController : Controller
{
  private readonly FactoryContext _db;

  public MachinesController(FactoryContext db)
  {
    _db = db;
  }
  
  public ActionResult Index()
  {
    return View(_db.Machines.ToList());
  }

  public ActionResult Create()
  {
    return View();
  }

  [HttpPost]
  public ActionResult Create(Machine machine)
  {
    if (!ModelState.IsValid)
    {
      return View(machine);
    }
    else
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }

  public ActionResult Details(int id)
  {
    ViewBag.Engineers = _db.Engineers.ToList();
    Machine thisMachine = _db.Machines
      .Include(machine => machine.JoinEntities)
      .ThenInclude(join => join.Engineer)
      .FirstOrDefault(machine => machine.MachineId == id);
    return View(thisMachine);
  }

  public ActionResult AddEngineer(int id)
  {
    Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
    ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
    return View(thisMachine);
  }

  [HttpPost]
  public ActionResult AddEngineer(Machine machine, int engineerId)
  {
    #nullable enable
    EngineerMachine? joinEntity =_db.EngineerMachines.FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
    #nullable disable
    if (joinEntity == null && engineerId != 0)
    {
      _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId });
      _db.SaveChanges();
    }
    return RedirectToAction("Details", new { id = machine.MachineId});
  }

  public ActionResult Edit(int id)
  {
    Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
    return View(thisMachine);
  }

  [HttpPost]
  public ActionResult Edit(Machine machine)
  {
    if (!ModelState.IsValid)
    {
      return View(machine);
    }
    else
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = machine.MachineId });
    }
  }

  public ActionResult Delete(int id)
  {
    Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
    return View(thisMachine);
  }

  [HttpPost, ActionName("Delete")]
  public ActionResult DeleteConfirmed(int id)
  {
    Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
    _db.Machines.Remove(thisMachine);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }

  [HttpPost]
  public ActionResult DeleteEngineer(int joinId)
  {
    EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
    _db.EngineerMachines.Remove(joinEntry);
    _db.SaveChanges();
    return RedirectToAction("Details", new { id = joinEntry.MachineId });
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Assign @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Select Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" />
}

<a href='@Url.Action("Index")'>
    <button type="button">Back to List</button>
</a>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer


<h2>Add an Engineer to the Team</h2>
<hr />

@using (Html.BeginForm())
{
  @Html.Label("Engineer Name ")
  <br>
  @Html.TextBoxFor(model => model.EngineerName)
  <p>@Html.ValidationMessageFor(model => model.EngineerName, "", new { @class = "text-danger" })</p> 

  <input type="submit" value="Add new hire"/>
}

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayName("Engineer Name"): @Html.DisplayFor(model => model.EngineerName)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to List", "Index")

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayName("Engineer Name"): @Html.DisplayFor(model => model.EngineerName)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This engineer does not have any current machines assigned to them.</p>
}
else
{
  <h4>Current machines assigned:</h4>
  <ul>
    @foreach (EngineerMachine join in Model.JoinEntities)
    {
      @using (Html.BeginForm("DeleteMachine", "Engineers"))
      {
        <li>
          @join.Machine.MachineName
          @Html.Hidden("joinId", @join.EngineerMachineId)
          <input type="submit" value="Delete" />
        </li>
      }
    }
  </ul>
}

@if (@ViewBag.Machines.Count == 0)
{
  <a href="">
    <button type="button" disabled="">No machines to assign</button>
  </a>
}
else
{
  <a href='@Url.Action("AddMachine", new { id = Model.EngineerId })'>
    <button type="button">Assign a Machine</button>
  </a>
}

<a href='@Url.Action("Delete", new { id = Model.EngineerId })'>
    <button type="button">Delete Engineer</button>
</a>
<a href='@Url.Action("Edit", new { id = Model.EngineerId })'>
    <button type="button">Edit Engineer</button>
</a>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Editing @Html.DisplayFor(model => model.EngineerName)</h2>
<hr />

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Updated Engineer Name") 
  <br>
  @Html.EditorFor(model => model.EngineerName)
  <p>@Html.ValidationMessageFor(model => model.EngineerName, "", new { @class = "text-danger" })</p> 

  <input type="submit" value="Save" />
}

<a href='@Url.Action("Index")'>
    <button type="button">Back to List</button>
</a>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models

<h3>Current Employed Engineers</h3>

@if (Model.Count == 0)
{
  <p>There are no engineers in the database.</p>
}
else
{
  <ul>
    @foreach (Engineer engineer in Model)
    {
      <li>@Html.ActionLink($"{engineer.EngineerName}", "Details", new { id = engineer.EngineerId })</li>
    }
  </ul>
}

<a href='@Url.Action("Create")'>
    <button type="button">Add a new Engineer</button>
</a>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models

<h1>Dr. Sillystringz's Factory</h1>

<hr />
<h4>Engineers</h4>
@if (Model["engineers"].Length == 0)
{
  <p>No engineers have been added yet!</p>
} 
else
{
  <ul>
    @foreach (Engineer engineer in @Model["engineers"])
    {
      <li>
        @Html.ActionLink(@engineer.EngineerName, "Details", "Engineers", new { id = @engineer.EngineerId })
      </li>
    }
  </ul>
}

<h4>Machines</h4>
@if (Model["machines"].Length == 0)
{
  <p>No machines have been added yet!</p>
} 
else
{
  <ul>
    @foreach (Machine machine in @Model["machines"])
    {
      <li>
        @Html.ActionLink(@machine.MachineName, "Details", "Machines", new { id = @machine.MachineId })
      </li>
    }
  </ul>
}

<hr />

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Assign @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}

<a href='@Url.Action("Index")'>
    <button type="button">Back to List</button>
</a>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine


<h2>Add a new machine</h2>
<hr />

@using (Html.BeginForm())
{
  @Html.Label("Machine Name")
  <br>
  @Html.TextBoxFor(model => model.MachineName)
  <p>@Html.ValidationMessageFor(model => model.MachineName, "", new { @class = "text-danger" })</p> 

  <input type="submit" value="Add new machine"/>
}

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayName("Machine Name"): @Html.DisplayFor(model => model.MachineName)
<hr />
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to List", "Index")

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayName("Machine Name"): @Html.DisplayFor(model => model.MachineName)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This machine does not have any current engineers assigned to them.</p>
}
else
{
  <h4>Current engineers assigned:</h4>
  <ul>
    @foreach (EngineerMachine join in Model.JoinEntities)
    {
      <li> 
      @using (Html.BeginForm("DeleteEngineer", "Machines"))
      {
        @join.Engineer.EngineerName
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete" />
      }
      </li>
    }
  </ul>
}

@if (@ViewBag.Engineers.Count == 0)
{
  <a href="">
    <button type="button" disabled="">No Engineers to assign</button>
  </a>
}
else
{
  <a href='@Url.Action("AddEngineer", new { id = Model.MachineId })'>
    <button type="button">Assign an Engineer</button>
  </a>
}

<a href='@Url.Action("Delete", new { id = Model.MachineId })'>
    <button type="button">Delete Machine</button>
</a>
<a href='@Url.Action("Edit", new { id = Model.MachineId })'>
    <button type="button">Edit Machine</button>
</a>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Editing @Html.DisplayFor(model => model.MachineName)</h2>
<hr />

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Updated Machine Name") 
  <br>
  @Html.EditorFor(model => model.MachineName)
  <p>@Html.ValidationMessageFor(model => model.MachineName, "", new { @class = "text-danger" })</p> 

  <input type="submit" value="Save" />
}

<a href='@Url.Action("Index")'>
    <button type="button">Back to List</button>
</a>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models

<h3>Current Machines</h3>

@if (Model.Count == 0)
{
  <p>There are no machines in the database.</p>
}
else
{
  <ul>
    @foreach (Machine machine in Model)
    {
      <li>@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId })</li>
    }
  </ul>
}

<a href='@Url.Action("Create")'>
    <button type="button">Add a new Machine</button>
</a>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Dr. Sillystringz's Factory</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
  <a class="navbar-brand">Dr. Sillystringz's Factory | </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
        <a class="nav-link enlarge" href='/'>Home</a>
        <a class="nav-link enlarge" href='/Engineers'>Engineers</a> 
        <a class="nav-link enlarge" href='/Machines'>Machines</a>
  </div>
</nav>
<div class="container">
  @RenderBody()
</div>
</body>

</html>